# Generated by Django 5.0.1 on 2024-01-05 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_file",
                    models.CharField(max_length=255, verbose_name="Название файла"),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Автор файла"
                    ),
                ),
                (
                    "name_column",
                    models.CharField(max_length=255, verbose_name="Название колонки"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["xlsx"])
                        ],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Статус обработки"),
                ),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Дата")),
            ],
        ),
    ]
