# Generated by Django 5.0.1 on 2024-01-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="status",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Статус обработки"
            ),
        ),
    ]
