# Generated by Django 5.0.1 on 2024-01-09 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_api", "0002_alter_filemodel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.FileField(
                upload_to="files_ml_api/",
                validators=[django.core.validators.FileExtensionValidator(["xlsx"])],
                verbose_name="Файл",
            ),
        ),
    ]
